base_url = "https://flux.carboxi.de"

# about me
author ="flux"
title = "flux:carboxide"
description = "Just a flow of carbons and oxygens in my body."

# disable sass and search index
compile_sass = false
build_search_index = false

# generate atom feed
feed_filenames = [ "atom.xml", "rss.xml" ]
generate_feeds = true

# enable tags
taxonomies = [
    {name = "tags", output = true}
]

# enable code highlighting
[markdown]
highlight_code = true
highlight_theme = "ascetic-white"

# extra stuff
[extra]
url = "flux.carboxi.de"
email = "flux@carboxi.de"
profile = "/thumbnail.png"
note = "There is nothing to know about me. I don't matter. What matters is what I write, and I write to know how I am evolving over time."
